import { test, expect } from '@playwright/test'
test.use({ baseURL: 'http://127.0.0.1:3001' })
const editor = page => page.locator('#editor')
async function append(page, text) {
  await expect(editor(page)).toHaveAttribute('data-ready', 'true')
  await editor(page).click()
  await expect(page.getByRole('textbox', { name: 'LVCE editor input' })).toBeFocused()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.insertText(text)
}

test('dev command automatically joins tabs and browsers with working WebRTC and cleanup', async ({ browser }) => {
  const context = await browser.newContext(), other = await browser.newContext()
  try {
    const host = await context.newPage()
    await host.goto('/')
    await host.getByLabel('Log verbosity').selectOption('debug')
    await expect(host.locator('#members')).toContainText('user-1 · host')
    // Opening a second tab copies sessionStorage in many browsers; dev ignores it.
    const guest = await context.newPage()
    await guest.goto('/')
    await guest.getByLabel('Log verbosity').selectOption('debug')
    await expect(guest.locator('#members')).toContainText('user-2 · reader')
    await expect(host.getByRole('log')).toContainText('WebRTC peer connected')
    await expect(guest.getByRole('log')).toContainText('WebRTC peer connected')
    await expect(editor(guest)).toHaveAttribute('data-readonly', 'true')
    await host.getByRole('button', { name: 'Allow user-2' }).click()
    await expect(guest.locator('#permission')).toHaveText('Write access')
    await append(host, 'Host peer edit')
    await expect(editor(guest)).toContainText('Host peer edit')
    await expect(guest.getByRole('log')).toContainText('WebRTC receive update')
    await append(guest, 'Guest peer edit')
    await expect(editor(host)).toContainText('Guest peer edit')
    await expect(host.getByRole('log')).toContainText('WebRTC receive update')
    await expect(host.getByRole('log')).toContainText('WebRTC receive cursor')
    await expect(host.locator('.remote-cursor-label')).toContainText('user-2')
    const colors = await host.locator('#members .member').evaluateAll(rows => rows.map(row => row.style.borderLeftColor))
    expect(new Set(colors).size).toBe(2)
    const late = await other.newPage()
    await late.goto('/')
    await expect(late.locator('#members')).toContainText('user-3 · reader')
    await expect(editor(late)).toContainText('Guest peer edit')
    await host.getByRole('button', { name: 'Revoke user-2' }).click()
    await expect(editor(guest)).toHaveAttribute('data-readonly', 'true')
    await guest.close()
    await expect(host.locator('#members')).toContainText('user-2 · reader · offline')
    await expect(host.getByRole('log')).toContainText('WebRTC peer disconnected')
    await expect(host.locator('.remote-cursor-label').filter({ hasText: 'user-2' })).toHaveCount(0)
    await late.reload()
    await expect(late.locator('#members')).toContainText('user-4 · reader')
    await expect(editor(late)).toContainText('Guest peer edit')
  } finally { await other.close(); await context.close() }
})
